worker_processes 1;

events {
    worker_connections 512;
}

http {
    include       /etc/nginx/mime.types;
    sendfile      on;

    keepalive_timeout 15;
    client_max_body_size 10M;

    access_log off;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    include /etc/nginx/conf.d/*.conf;
}
