# nginx/conf.d/app1.conf

server {
    listen 80;
    server_name guiahipertrofia.fellahost.com;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name guiahipertrofia.fellahost.com;

    ssl_certificate /etc/letsencrypt/live/guiahipertrofia.fellahost.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/guiahipertrofia.fellahost.com/privkey.pem;

    include /etc/nginx/snippets/ssl.conf;

    location / {
        proxy_pass http://frontend:80;
        include /etc/nginx/snippets/proxy.conf;
    }

    location /api/ {
        proxy_pass http://backend:8080/;
        include /etc/nginx/snippets/proxy.conf;
    }
}
