version = 5.4.0
archive_dir = /etc/letsencrypt/archive/guiahipertrofia.fellahost.com
cert = /etc/letsencrypt/live/guiahipertrofia.fellahost.com/cert.pem
privkey = /etc/letsencrypt/live/guiahipertrofia.fellahost.com/privkey.pem
chain = /etc/letsencrypt/live/guiahipertrofia.fellahost.com/chain.pem
fullchain = /etc/letsencrypt/live/guiahipertrofia.fellahost.com/fullchain.pem
[renewalparams]
account = 409ac3b93351facdb4e2be1d91bd020b
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
guiahipertrofia.fellahost.com = /var/www/certbot
